---
- name: Include Variables from vars folder
  ansible.builtin.include_vars: ../vars/variables.yml
- name: Run check_status.sql
  become: true
  become_user: "{{ oracle_user }}"
  ansible.builtin.shell: |
    echo exit | sqlplus / as sysdba @{{ oracle_stage }}/check_status.sql
  register: status_result
  environment: "{{ env }}"
  tags: check_status

- ansible.builtin.debug:
    var: status_result.stdout_lines
    cmd: ""
  tags: check_status

- name: Start Oracle DB
  become: true
  become_user: "{{ oracle_user }}"
  ansible.builtin.shell: |
    echo 'startup;' | sqlplus / as sysdba
  environment: "{{ env }}"
  register: startdb_output
  when: "'OPEN' not in status_result.stdout_lines"
  tags:
    - startdb

- ansible.builtin.debug:
    var: startdb_output.stdout_lines
    cmd: ""
  when: "'OPEN' not in status_result.stdout_lines"
