---
- name: Include Variables from vars folder
  ansible.builtin.include_vars: ../vars/variables.yml
- name: Run check_status.sql
  become: true
  become_user: "{{ oracle_user }}"
  ansible.builtin.shell: |
    echo exit | sqlplus / as sysdba @{{ oracle_stage }}/check_status.sql
  register: status_result1
  environment: "{{ env }}"
  tags: check_status

- ansible.builtin.debug:
    var: status_result1.stdout_lines
    cmd: ""
  tags: check_status

- name: Shutdown database
  become: true
  become_user: "{{ oracle_user }}"
  ansible.builtin.shell: |
    echo 'shutdown immediate;' | sqlplus / as sysdba
  environment: "{{ env }}"
  register: shutdown_output
  when: "'OPEN' in status_result1.stdout_lines"
  tags:
    - shutdown

- ansible.builtin.debug:
    var: shutdown_output.stdout_lines
    cmd: ""
  when: "'OPEN' in status_result1.stdout_lines"
